# Nama dari workflow ini
name: ML CI/CD Pipeline with Docker

# Event yang akan memicu workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definisi jobs
jobs:
  # Job 1: Membangun dan Mendorong Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-ml-model:latest

  # Job 2: Melatih Model Menggunakan Docker & Menyimpan Artifact
  train-and-save:
    # Job ini baru akan berjalan setelah job 'build' selesai
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-ml-model:latest

      - name: Run training script inside Docker container
        run: docker run --name ml-container ${{ secrets.DOCKERHUB_USERNAME }}/simple-ml-model:latest

      - name: Copy trained model from container
        run: docker cp ml-container:/app/model.joblib .

      - name: Upload Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-ml-model
          path: model.joblib
